spring.application.name=luSolrCorrectionService

spring.profiles.active=dev
server.port=18081
data.solr.collection1=collection1
data.solr.edition=edition
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.default-produces-media-type=application/json
